# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from exosystem/Sysstatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Sysstatus(genpy.Message):
  _md5sum = "a24a13feba27c82997977933cd4b8af4"
  _type = "exosystem/Sysstatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 record_flag
float32 theta_m1
float32 theta_l1
float32 delta_theta_r1
float32 Trr_ad
float32 theta_m2
float32 theta_l2
float32 delta_theta_r2
float32 Trr_cf"""
  __slots__ = ['record_flag','theta_m1','theta_l1','delta_theta_r1','Trr_ad','theta_m2','theta_l2','delta_theta_r2','Trr_cf']
  _slot_types = ['int16','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       record_flag,theta_m1,theta_l1,delta_theta_r1,Trr_ad,theta_m2,theta_l2,delta_theta_r2,Trr_cf

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Sysstatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.record_flag is None:
        self.record_flag = 0
      if self.theta_m1 is None:
        self.theta_m1 = 0.
      if self.theta_l1 is None:
        self.theta_l1 = 0.
      if self.delta_theta_r1 is None:
        self.delta_theta_r1 = 0.
      if self.Trr_ad is None:
        self.Trr_ad = 0.
      if self.theta_m2 is None:
        self.theta_m2 = 0.
      if self.theta_l2 is None:
        self.theta_l2 = 0.
      if self.delta_theta_r2 is None:
        self.delta_theta_r2 = 0.
      if self.Trr_cf is None:
        self.Trr_cf = 0.
    else:
      self.record_flag = 0
      self.theta_m1 = 0.
      self.theta_l1 = 0.
      self.delta_theta_r1 = 0.
      self.Trr_ad = 0.
      self.theta_m2 = 0.
      self.theta_l2 = 0.
      self.delta_theta_r2 = 0.
      self.Trr_cf = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_h8f().pack(_x.record_flag, _x.theta_m1, _x.theta_l1, _x.delta_theta_r1, _x.Trr_ad, _x.theta_m2, _x.theta_l2, _x.delta_theta_r2, _x.Trr_cf))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.record_flag, _x.theta_m1, _x.theta_l1, _x.delta_theta_r1, _x.Trr_ad, _x.theta_m2, _x.theta_l2, _x.delta_theta_r2, _x.Trr_cf,) = _get_struct_h8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_h8f().pack(_x.record_flag, _x.theta_m1, _x.theta_l1, _x.delta_theta_r1, _x.Trr_ad, _x.theta_m2, _x.theta_l2, _x.delta_theta_r2, _x.Trr_cf))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 34
      (_x.record_flag, _x.theta_m1, _x.theta_l1, _x.delta_theta_r1, _x.Trr_ad, _x.theta_m2, _x.theta_l2, _x.delta_theta_r2, _x.Trr_cf,) = _get_struct_h8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_h8f = None
def _get_struct_h8f():
    global _struct_h8f
    if _struct_h8f is None:
        _struct_h8f = struct.Struct("<h8f")
    return _struct_h8f
